# Datenstrom Yellow extension settings

Extension: Copenhagen
Version: 1.0.1
Description: Copenhagen is a beautiful theme.
Designer: Anna Svensson
Tag: theme
DownloadUrl: https://github.com/annaesvensson/yellow-copenhagen/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-copenhagen
DocumentationLanguage: en, de, sv
Published: 2026-09-25 19:06:45
Status: maintained
system/workers/copenhagen.php: copenhagen.php, create, update
system/themes/copenhagen.css: copenhagen.css, create, update, careful
system/themes/copenhagen.png: copenhagen.png, create
